# Generated by Django 4.0.2 on 2022-04-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_alter_parseurl_subpageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseurl',
            name='AllJSON',
            field=models.JSONField(null=True),
        ),
    ]
