# Generated by Django 4.0.2 on 2022-04-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_parseurl_alljson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parseurl',
            old_name='AllJSON',
            new_name='JSON',
        ),
    ]
