# Generated by Django 4.0.2 on 2022-03-21 19:38

import base.services
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, unique=True)),
                ('Description', models.TextField(blank=True, max_length=10000, null=True)),
                ('PubDate', models.DateTimeField(auto_now_add=True)),
                ('ChangeDate', models.DateTimeField(auto_now_add=True)),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_game', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link', models.URLField()),
                ('Image', models.ImageField(upload_to=base.services.get_path_upload_post_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'gif', 'png']), base.services.validate_size_image])),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_links', to='posts.postgame')),
            ],
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to=base.services.get_path_upload_post_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'gif', 'png']), base.services.validate_size_image])),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='posts.postgame')),
            ],
        ),
    ]
