# Generated by Django 4.0.2 on 2022-03-24 11:35

import base.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlink',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=base.services.get_path_upload_post_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'gif', 'png']), base.services.validate_size_image]),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='Link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='Text',
            field=models.CharField(max_length=255),
        ),
    ]
