# Generated by Django 4.0.2 on 2022-03-21 19:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_postcomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComments',
            new_name='PostComment',
        ),
        migrations.RenameModel(
            old_name='PostImages',
            new_name='PostImage',
        ),
        migrations.RenameModel(
            old_name='PostLinks',
            new_name='PostLink',
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'verbose_name': 'Post Comments', 'verbose_name_plural': 'Post Comments'},
        ),
        migrations.AlterModelOptions(
            name='postgame',
            options={'verbose_name': 'Game Posts', 'verbose_name_plural': 'Game Posts'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Post images', 'verbose_name_plural': 'Post images'},
        ),
        migrations.AlterModelOptions(
            name='postlink',
            options={'verbose_name': 'Post links', 'verbose_name_plural': 'Post links'},
        ),
    ]
