# Generated by Django 4.0.2 on 2022-03-24 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_postlink_image_alter_postlink_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikedislike',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_dislike_user', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
