# Generated by Django 4.0.2 on 2022-03-21 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_rename_postcomments_postcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.BooleanField(default=False)),
                ('CommentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_dislike_comment', to='posts.postgame')),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_dislike_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment like / dislike',
                'verbose_name_plural': 'Comment like / dislike',
            },
        ),
    ]
