# Generated by Django 4.0.2 on 2022-03-25 12:29

import base.services
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_commentlikedislike_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlikedislike',
            name='id',
        ),
        migrations.AlterField(
            model_name='commentlikedislike',
            name='Email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='like_dislike_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='Image',
            field=models.ImageField(upload_to=base.services.get_path_upload_post_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'gif']), base.services.validate_size_image]),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=base.services.get_path_upload_post_link_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'gif', 'png']), base.services.validate_size_image]),
        ),
    ]
