# Generated by Django 4.0.2 on 2022-03-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_commentlikedislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': 'TagsXD',
            },
        ),
        migrations.AlterModelOptions(
            name='commentlikedislike',
            options={'verbose_name': 'Comment like/dislike', 'verbose_name_plural': 'Comment like/dislike'},
        ),
        migrations.AddField(
            model_name='postgame',
            name='Tags',
            field=models.ManyToManyField(to='posts.PostTag'),
        ),
    ]
