# Generated by Django 4.0.2 on 2022-03-22 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
        ('posts', '0006_postrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookmarks',
            fields=[
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Bookmarks', models.ManyToManyField(to='posts.PostTag')),
            ],
            options={
                'verbose_name': 'User bookmarks',
                'verbose_name_plural': 'User bookmarks',
            },
        ),
    ]
