# Generated by Django 4.0.2 on 2022-03-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_userbookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmarks',
            name='Bookmarks',
            field=models.ManyToManyField(to='posts.PostGame'),
        ),
    ]
